## NumPy 一维数组

In [ ]:
import numpy as np

arr1 = np.array([0, 1, 2, 3, 4])
arr2 = np.arange(5)
arr2

## NumPy 二维数组

### 二维数据的行列长度需要相等

In [ ]:
import numpy as np

# error
# arr = np.array([np.arange(2),np.arange(3)])

arr = np.array([np.arange(2), np.arange(2)])
# arr.shape
arr

## NumPy 一维数组切片和索引

In [ ]:
import numpy as np

a = np.arange(10) ** 3
# array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

# a[2]
# a[2:]
# a[2:4] # 包前不包后

# a[2:4] = 1000
# a[:-4] = -100
# a[-4:] = 80
# a[:6:2] = 33
# a[::-1] # no effect need assign to object

array = np.array([[1, 2], [4, 5]])
x = array[0, 1]  # np.int64(2)
c = array[0, 0]
b = array[1, 1]

#arr2 = [1,2,3,4,5]
arr2 = np.arange(5)
arr2 = arr2[::-1]  # reverse
arr2

### 改变数组形状

In [ ]:
arr = np.arange(24).reshape(2, 3, 4)
#print(arr.ravel())
#print(arr.flatten())

#arr.resize(3,8)
arr.resize((3, 8))


## 堆叠数组

In [ ]:
aa = np.arange(9).reshape(3, 3)
bb = aa * 3
#print(aa)
#print(bb)

cc = np.hstack((aa, bb))
print(cc)

xx = np.concatenate((aa, bb))
print(xx)

dd = np.concatenate((aa, bb), axis=1)
print(dd)



## 拆分数组

In [ ]:
dd = np.arange(9).reshape(3, 3)
print(dd)

# np.hsplit(dd, 3)
# np.split(dd, 3, axis=1)

# np.vsplit(dd, 3)

np.split(dd, 3, axis=0)


## 数组转置

In [ ]:
uu = np.arange(24).reshape(2, 12)
# print(uu)

zz = uu.reshape(6, 4)
print(zz)

o = zz.T
print(o)

qq = zz.reshape(4, 6)
print(qq)

## NumPy 高级索引

In [ ]:
tt = np.arange(24).reshape(4, 6)
print(tt)

#ppp = tt[:3, 3:]
#print(ppp)

#e = tt[:3,[1,2,3,4]]
#print(e)

aa = tt[..., 2:]
# aa = tt[, 2:] #索引全选 不能空着
print(aa)

### 布尔索引

In [ ]:
nn = np.arange(12).reshape(4, 3)
print(nn)

print(nn[nn > 5])

### Raccoon 小浣熊图片

In [ ]:
import numpy as np
import scipy.misc
import matplotlib.pyplot as plt

# 小浣熊过时了
face = np.array(scipy.misc.face())
print(face.shap)
plt.imshow(face)
plt.show()


## NumPy 统计函数

In [6]:
import numpy as np

array = np.array([[3, 7, 5], [8, 4, 3], [2, 4, 9]])
print(array)

print(np.amin(array, axis=1))
print(np.amin(array, axis=0))

print(np.amax(array, axis=1))
print(np.amax(array, axis=0))

print(np.amax(array))

[[3 7 5]
 [8 4 3]
 [2 4 9]]
[3 3 2]
[2 4 3]
[7 8 9]
[8 7 9]
9


#### sort() argsort() 返回数组值从小到大的索引值

In [10]:
import numpy as np

arr = np.array([[3, 7, 5], [8, 4, 3]])
#arr = np.sort(arr)
#print(arr)

y = np.argsort(arr)
print(y)


[[0 2 1]
 [2 1 0]]


### NumPy 中的统计函数 where()

In [15]:
import numpy as np

xxx = np.arange(9.).reshape(3, 3)
print(xxx)

y = np.where(xxx > 3)
print(y)

print(xxx[y])


[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]
(array([1, 1, 2, 2, 2]), array([1, 2, 0, 1, 2]))
[4. 5. 6. 7. 8.]


### NumPy 中的统计函数 extract()

In [23]:
import numpy as np

w = np.arange(9.).reshape(3, 3)
print(w)

condition_arr = np.mod(w, 2) == 0
print(condition_arr)

rrr = np.extract(condition_arr, w)
print(rrr)

condition_arr = (w >= 4)
print(condition_arr)

ff = np.extract(condition_arr, w)
print(ff)

[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]
[[ True False  True]
 [False  True False]
 [ True False  True]]
[0. 2. 4. 6. 8.]
[[False False False]
 [False  True  True]
 [ True  True  True]]
[4. 5. 6. 7. 8.]


#### NumPy 算数平均值

In [24]:
import numpy as np

ddd = np.array([[1, 2, 3], [3, 4, 5], [4, 5, 6]])
print(ddd)


[[1 2 3]
 [3 4 5]
 [4 5 6]]


#### 求算数平均值

In [32]:
import numpy as np

oo = np.array([[1, 2, 3], [3, 4, 5], [4, 5, 6]])
print(oo)

print(np.mean(oo))

# axis=0 竖直方向
print(np.mean(oo, axis=0))

# axis=1 水平方向
print(np.mean(oo, axis=1))

# ----- average -----

uuu = oo.flatten()
print(np.average(uuu))


[[1 2 3]
 [3 4 5]
 [4 5 6]]
3.6666666666666665
[2.66666667 3.66666667 4.66666667]
[2. 4. 5.]
3.6666666666666665
