In [1]:
import numpy as np

array = np.arange(1, 13).reshape(3, 4)
mean_val = np.mean(array)
std_val = np.std(array)

print(array)
print("平均值:", mean_val)
print("标准差:", std_val)

array[array < mean_val] = -1
print(array)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
平均值: 6.5
标准差: 3.452052529534663
[[-1 -1 -1 -1]
 [-1 -1  7  8]
 [ 9 10 11 12]]
